name: TestBuild

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt-openj9'
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/BlackOnion-Bot/.gradle/caches
            ~/BlackOnion-Bot/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: |
          cd /home/runner/work/BlackOnion-Bot/BlackOnion-Bot/BlackOnion-Bot
          chmod +x ./gradlew
          ./gradlew shadowJar -Dorg.gradle.jvmargs="-Xmx4G -Xms2G -Xshareclasses -XX:SharedCachedHardLimit=200m -Xscmx60m -XX:+IdleTuningGcOnIdle -Xquickstart -Xtune:virtualized -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError" -Dfile.encoding=UTF-8
      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        run: |
          rm -f ~/BlackOnion-Bot/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/BlackOnion.Bot/.gradle/caches/modules-2/gc.properties
