name: Build & Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Packages Docker Registry
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the version
        id: get_version
        run: |
          REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          VERSION=$(echo $GITHUB_REF | grep -o '[^/]*$')
          FULL_VERSION=$(echo $GITHUB_REF | cut -d / -f 3-)
          echo ::set-output name=REPO::$REPO
          echo ::set-output name=VERSION::$VERSION
          if [[ $FULL_VERSION =~ ^v[0-9]+.[0-9]+.[0-9]+$ ]]; then
            TAG="latest"
          elif [[ $FULL_VERSION =~ ^b[0-9]+.[0-9]+.[0-9]+$ ]]; then
            TAG="latest-beta"
          else
            TAG="latest-dev"
          fi
          echo ::set-output name=TAG::$TAG
          echo "Full Version: $FULL_VERSION | Version: $VERSION | Tag: $TAG"

      - name: Build and push
        uses: docker/build-push-action@v3
        env:
          REPO: ${{ steps.get_version.outputs.REPO }}
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          TAG: ${{ steps.get_version.outputs.TAG }}
        with:
          push: ${ ${{ steps.get_version.outputs.TAG }} == "latest" || ${{ steps.get_version.outputs.TAG }} == "latest-beta" }
          cache-from: type=gha
          cache-to: type=gha
          tags: |
            ghcr.io/$REPO:$VERSION
            ghcr.io/$REPO:$TAG

  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test jacocoTestReport
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          path: build/reports/tests/test/
          name: Test Report
          retention-days: 14
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          path: build/reports/jacoco/test/
          name: Coverage Report
          retention-days: 14