name: BuildAndRelease

on: push
#   push:
#    tags:
#    - 'v*'

jobs:
  dobuild:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
#      - name: Login to Github Packages Docker Registry
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the version
        id: get_version
        #run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        run: echo ::set-output name=VERSION::moin
      - name: Build docker image
        run: |
          REPO=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')
          # ${{ secrets.GITHUB_TOKEN }}
          docker build -t ghcr.io/$REPO/bot:${{ steps.get_version.outputs.VERSION }} -t ghcr.io/$REPO/bot:latest .

  notify-server:
    needs: dobuild
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
      run: |
        answer=$(curl --location --request POST 'https://www.black-onion.com'"${API_ENDPOINT}"'' --header 't0k3n: '"${API_KEY}"'' -A "BlackOnion Action Client (yes actually a real one)")
        if [[ $answer == *"200-success |"* ]];
        then
          echo Successfully connected and started the script!
          exit 0
        else
          echo Could not connect!
          exit 1
        fi
