name: Validate JSON Syntax

on:
  push:
    paths:
      - '**.json'
  pull_request:
    paths:
      - '**.json'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"
      - name: print shit
        if: always()
        run: echo ${{ steps.test.outputs.failed_files }}
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ failed() }}
        with:
          labels: jsoninvalid
      - uses: mshick/add-pr-comment@v1
        if: ${{ failed() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            Invalid JSONs detected.
            Files affected: ${{ steps.test.outputs.failed_files }}
          allow-repeats: true
